repalcing get with newget
Testing f..
Trying concrete values: {}
in function newget


['_Query__all_equivs', '__class__', '__clause_element__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__hash__', '__init__', '__iter__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_adapt_all_clauses', '_adapt_clause', '_adapt_col_list', '_adapt_polymorphic_element', '_adjust_for_single_inheritance', '_attributes', '_autoflush', '_clone', '_compile_context', '_compound_eager_statement', '_conditional_options', '_connection_from_session', '_correlate', '_criterion', '_current_path', '_distinct', '_enable_assertions', '_enable_eagerloads', '_enable_single_crit', '_entities', '_entity_zero', '_execute_and_instances', '_execution_options', '_filter_aliases', '_from_obj', '_from_obj_alias', '_from_selectable', '_get_condition', '_get_options', '_group_by', '_having', '_invoke_all_eagers', '_join', '_join_entities', '_join_left_to_right', '_join_to_left', '_joinpath', '_joinpoint', '_joinpoint_zero', '_limit', '_lockmode', '_lockmode_lookup', '_mapper_adapter_map', '_mapper_entities', '_mapper_loads_polymorphically_with', '_mapper_zero', '_mapper_zero_or_none', '_no_clauseelement_condition', '_no_criterion_condition', '_no_limit_offset', '_no_select_modifiers', '_no_statement_condition', '_offset', '_only_entity_zero', '_only_full_mapper_zero', '_only_load_props', '_only_mapper_zero', '_options', '_order_by', '_params', '_polymorphic_adapters', '_populate_existing', '_prefixes', '_prepare_right_side', '_refresh_state', '_reset_joinpoint', '_reset_polymorphic_adapter', '_select_args', '_select_from_entity', '_set_entities', '_set_entity_selectables', '_set_select_from', '_should_log_debug', '_should_log_info', '_should_nest_selectable', '_simple_statement', '_statement', '_update_joinpoint', '_values', '_version_check', '_with_current_path', '_with_hints', '_with_invoke_all_eagers', '_with_labels', '_with_options', '_yield_per', 'add_column', 'add_columns', 'add_entity', 'all', 'as_scalar', 'autoflush', 'column_descriptions', 'correlate', 'count', 'cte', 'delete', 'distinct', 'enable_assertions', 'enable_eagerloads', 'except_', 'except_all', 'execution_options', 'exists', 'filter', 'filter_by', 'first', 'from_self', 'from_statement', 'get', 'group_by', 'having', 'instances', 'intersect', 'intersect_all', 'join', 'label', 'limit', 'logger', 'merge_result', 'offset', 'one', 'options', 'order_by', 'outerjoin', 'params', 'populate_existing', 'prefix_with', 'reset_joinpoint', 'scalar', 'select_entity_from', 'select_from', 'selectable', 'session', 'slice', 'statement', 'subquery', 'union', 'union_all', 'update', 'value', 'values', 'whereclause', 'with_entities', 'with_hint', 'with_labels', 'with_lockmode', 'with_parent', 'with_polymorphic', 'with_session', 'with_transformation', 'yield_per']
 -> None
Test generated 0 branches:
Stopping after 1 iterations
Missing some cases for f: set([924, 22])
Testing g..
Trying concrete values: {}
in function newget


['_Query__all_equivs', '__class__', '__clause_element__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__hash__', '__init__', '__iter__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_adapt_all_clauses', '_adapt_clause', '_adapt_col_list', '_adapt_polymorphic_element', '_adjust_for_single_inheritance', '_attributes', '_autoflush', '_clone', '_compile_context', '_compound_eager_statement', '_conditional_options', '_connection_from_session', '_correlate', '_criterion', '_current_path', '_distinct', '_enable_assertions', '_enable_eagerloads', '_enable_single_crit', '_entities', '_entity_zero', '_execute_and_instances', '_execution_options', '_filter_aliases', '_from_obj', '_from_obj_alias', '_from_selectable', '_get_condition', '_get_options', '_group_by', '_having', '_invoke_all_eagers', '_join', '_join_entities', '_join_left_to_right', '_join_to_left', '_joinpath', '_joinpoint', '_joinpoint_zero', '_limit', '_lockmode', '_lockmode_lookup', '_mapper_adapter_map', '_mapper_entities', '_mapper_loads_polymorphically_with', '_mapper_zero', '_mapper_zero_or_none', '_no_clauseelement_condition', '_no_criterion_condition', '_no_limit_offset', '_no_select_modifiers', '_no_statement_condition', '_offset', '_only_entity_zero', '_only_full_mapper_zero', '_only_load_props', '_only_mapper_zero', '_options', '_order_by', '_params', '_polymorphic_adapters', '_populate_existing', '_prefixes', '_prepare_right_side', '_refresh_state', '_reset_joinpoint', '_reset_polymorphic_adapter', '_select_args', '_select_from_entity', '_set_entities', '_set_entity_selectables', '_set_select_from', '_should_log_debug', '_should_log_info', '_should_nest_selectable', '_simple_statement', '_statement', '_update_joinpoint', '_values', '_version_check', '_with_current_path', '_with_hints', '_with_invoke_all_eagers', '_with_labels', '_with_options', '_yield_per', 'add_column', 'add_columns', 'add_entity', 'all', 'as_scalar', 'autoflush', 'column_descriptions', 'correlate', 'count', 'cte', 'delete', 'distinct', 'enable_assertions', 'enable_eagerloads', 'except_', 'except_all', 'execution_options', 'exists', 'filter', 'filter_by', 'first', 'from_self', 'from_statement', 'get', 'group_by', 'having', 'instances', 'intersect', 'intersect_all', 'join', 'label', 'limit', 'logger', 'merge_result', 'offset', 'one', 'options', 'order_by', 'outerjoin', 'params', 'populate_existing', 'prefix_with', 'reset_joinpoint', 'scalar', 'select_entity_from', 'select_from', 'selectable', 'session', 'slice', 'statement', 'subquery', 'union', 'union_all', 'update', 'value', 'values', 'whereclause', 'with_entities', 'with_hint', 'with_labels', 'with_lockmode', 'with_parent', 'with_polymorphic', 'with_session', 'with_transformation', 'yield_per']
0 -> None
Test generated 0 branches:
Stopping after 1 iterations
Missing some cases for g: set(['firstthing', 'yy', 'another'])
